return {
    {'EdenEast/nightfox.nvim', },
    {'nvim-lua/plenary.nvim'},
    {'nvim-telescope/telescope.nvim'},
    {'nvim-telescope/telescope-fzf-native.nvim', build='make' },
    {'nvim-tree/nvim-tree.lua', opts={} },
    {'akinsho/toggleterm.nvim', lazy = true},
    {'neoclide/coc.nvim', branch='release' },
    {'nvim-treesitter/nvim-treesitter', build=':TSUpdate' },
    {'ahmedkhalf/project.nvim'},
    {'ahmedkhalf/lsp-rooter.nvim', opts={} },
    {'terrortylor/nvim-comment', lazy = true},
    {'tpope/vim-fugitive', 
        cmd = "G",
        lazy = true
    },
    {'windwp/nvim-projectconfig', lazy = true},
    {'MrcJkb/haskell-tools.nvim', lazy = true},
    {'mfussenegger/nvim-dap', lazy = true},
    {'ThePrimeagen/harpoon', lazy = true},
    {'nvim-tree/nvim-web-devicons'},
}
